name: foodix
description: "Foodix is a Food App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  device_preview: ^1.3.1
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.3
  google_sign_in: ^7.1.0
  logger: ^2.6.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  supabase_flutter: ^2.9.1
  font_awesome_flutter: ^10.8.0
  firebase_database: ^11.3.8
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  flutter_svg: ^2.2.0
  failure_handler:
    git:
      url: https://github.com/SaifAllahGharib/failure_handler.git
      ref: master
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true