// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTXMiaPtgpQCO4Q6Eil9LeFREhTW3iBEc',
    appId: '1:899004025563:android:b6b209e150022349319afe',
    messagingSenderId: '899004025563',
    projectId: 'yummyhome-e338e',
    databaseURL: 'https://yummyhome-e338e-default-rtdb.firebaseio.com',
    storageBucket: 'yummyhome-e338e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5usVLUYO6rfV3nTDacmWwHThlYnLdobs',
    appId: '1:899004025563:ios:67a5aede52c0f8ab319afe',
    messagingSenderId: '899004025563',
    projectId: 'yummyhome-e338e',
    databaseURL: 'https://yummyhome-e338e-default-rtdb.firebaseio.com',
    storageBucket: 'yummyhome-e338e.firebasestorage.app',
    androidClientId: '899004025563-gc599ekph0d72djc03inr9vf3ie83q55.apps.googleusercontent.com',
    iosClientId: '899004025563-o0aha5aqr27u9oc24okvelrbc6apmhj4.apps.googleusercontent.com',
    iosBundleId: 'com.foodix',
  );

}